# Generated by Django 4.2.2 on 2023-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
